### ISSUE TITLE
TopicModelling Notebook - What's the difference between installing pyldavis one or the other way?

### ISSUE THREAD

**Issue by JuliaDatakube** [digitaltxtlab/CLEAR#4]
Please explain when a user should do one or the other command.

pyLDAvis
conda install -c conda-forge pyldavis
or
conda install -c conda-forge/label/gcc7 pyldavis

=> It's for TopicModelling notebook

**Comment by Zehui127** [comment]
Sure, I will add a comment to the notebook.  The first command "conda install -c conda-forge pyldavis" will work, but in some version of the anaconda, it may require to use the second command "conda install -c conda-forge/label/gcc7 pyldavis", which specify the label of this package

**Comment by JuliaDatakube** [comment]
Great, thank you!
